sudo: required

language: cpp

compiler: clang

before_install:
 - sudo apt-get update
 - sudo apt-get install -y libgtest-dev
 - cd /usr/src/gtest 
 - sudo CXX=clang++ CC=clang cmake .
 - sudo CXX=clang++ CC=clang cmake --build .
 - sudo mv libg* /usr/local/lib/
 - cd -

script: true
